---
    - name: install java and update cache
      apt:
        name: openjdk-11-jdk
        update_cache: yes

    - name: Download ElasticSearch key
      apt_key: 
        url: '{{ key_url }}'
        keyring: /usr/share/keyrings/elasticsearch-keyring.gpg

    - name: install apt-transport-https
      apt:
        name: apt-transport-https
        state: present
        update_cache: yes
    
    - name: insert signnature
      lineinfile:
        path: '/etc/apt/sources.list.d/elastic-{{ version }}.x.list'
        line: 'deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/{{ version }}.x/apt stable main'
        create: yes
    
    - name: install elasticsearch
      apt:
        name: elasticsearch
        state: present
        update_cache: true

    - name: configure elasticsearch
      template: 
        src: elasticsearch.yml.j2
        dest: /etc/elasticsearch/elasticsearch.yml
        
      notify: 
        - daemon_reload
        - Start_ES